function [fitresult, gof] = createFit(AverageRSSIdBm, AcutalDistancem)
%CREATEFIT(AVERAGERSSIDBM,ACUTALDISTANCEM)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : AverageRSSIdBm
%      Y Output: AcutalDistancem
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Oct-2021 09:52:13


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( AverageRSSIdBm, AcutalDistancem );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.00160419329244048 -0.0939684765869806];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'AcutalDistancem vs. AverageRSSIdBm', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel AverageRSSIdBm
ylabel AcutalDistancem
grid on


