function [fitresult, gof] = createFit(RSSI, Distance)
%CREATEFIT1(RSSI,DISTANCE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : RSSI
%      Y Output: Distance
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Oct-2021 20:21:27


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( RSSI, Distance );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.0336520798880578 -0.0600756600776581];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Distance vs. RSSI', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel RSSI
ylabel Distance
grid on


